//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace damlaucus.Entities {
    
    
    [TableOptions(TableName="E_damlaucus_Form2")]
    public class E_damlaucus_Form2Entity : FormEntity<E_damlaucus_Form2Entity> {
        
        private Bimser.Framework.Domain.DataField<decimal> _BAGAJ;
        
        private Bimser.Framework.Domain.DataField<decimal> _MILUCRET;
        
        private Bimser.Framework.Domain.DataField<decimal> _NumberBox1;
        
        private E_damlaucus_Form2VREntity _VersionEntity;
        
        private RDEntityCollection<E_damlaucus_Form2RDEntity, E_damlaucus_Form2RDMLEntity> _RD;
        
        private RDCEntityCollection<E_damlaucus_Form2RDCEntity, E_damlaucus_Form2RDCMLEntity> _RDC;
        
        private GridEntityCollection<E_damlaucus_Form2_DataGrid1Entity, E_damlaucus_Form2_DataGrid1MLEntity, E_damlaucus_Form2_DataGrid1SLEntity, E_damlaucus_Form2_DataGrid1SLMLEntity> _E_damlaucus_Form2_DataGrid1;
        
        public E_damlaucus_Form2Entity() {
            this.VersionEntity = new E_damlaucus_Form2VREntity();
            this.RD = new RDEntityCollection<E_damlaucus_Form2RDEntity, E_damlaucus_Form2RDMLEntity>();
            this.RDC = new RDCEntityCollection<E_damlaucus_Form2RDCEntity, E_damlaucus_Form2RDCMLEntity>();
            this.E_damlaucus_Form2_DataGrid1 = new GridEntityCollection<E_damlaucus_Form2_DataGrid1Entity, E_damlaucus_Form2_DataGrid1MLEntity, E_damlaucus_Form2_DataGrid1SLEntity, E_damlaucus_Form2_DataGrid1SLMLEntity>();
            this.E_damlaucus_Form2_DataGrid1.MLEntityEnabled = true;
            this.E_damlaucus_Form2_DataGrid1.SLEntityEnabled = false;
        }
        
        [ColumnOptionsAttribute(Name="BAGAJ", Mandatory=true)]
        public Bimser.Framework.Domain.DataField<decimal> BAGAJ {
            get {
                return this._BAGAJ;
            }
            set {
                this._BAGAJ = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="MILUCRET", Mandatory=true)]
        public Bimser.Framework.Domain.DataField<decimal> MILUCRET {
            get {
                return this._MILUCRET;
            }
            set {
                this._MILUCRET = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="NumberBox1", Mandatory=true)]
        public Bimser.Framework.Domain.DataField<decimal> NumberBox1 {
            get {
                return this._NumberBox1;
            }
            set {
                this._NumberBox1 = value;
            }
        }
        
        public E_damlaucus_Form2VREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_damlaucus_Form2RDEntity, E_damlaucus_Form2RDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_damlaucus_Form2RDCEntity, E_damlaucus_Form2RDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public GridEntityCollection<E_damlaucus_Form2_DataGrid1Entity, E_damlaucus_Form2_DataGrid1MLEntity, E_damlaucus_Form2_DataGrid1SLEntity, E_damlaucus_Form2_DataGrid1SLMLEntity> E_damlaucus_Form2_DataGrid1 {
            get {
                return this._E_damlaucus_Form2_DataGrid1;
            }
            set {
                this._E_damlaucus_Form2_DataGrid1 = value;
            }
        }
    }
    
    [TableOptions(TableName="E_damlaucus_Form2_DataGrid1")]
    public class E_damlaucus_Form2_DataGrid1Entity : GridEntity<E_damlaucus_Form2_DataGrid1Entity, E_damlaucus_Form2_DataGrid1MLEntity, E_damlaucus_Form2_DataGrid1SLEntity, E_damlaucus_Form2_DataGrid1SLMLEntity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _DGID;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _ENLEM;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _BOYLAM;
        
        public E_damlaucus_Form2_DataGrid1Entity() {
        }
        
        [ColumnOptionsAttribute(Name="DGID", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> DGID {
            get {
                return this._DGID;
            }
            set {
                this._DGID = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="ENLEM", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> ENLEM {
            get {
                return this._ENLEM;
            }
            set {
                this._ENLEM = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="BOYLAM", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> BOYLAM {
            get {
                return this._BOYLAM;
            }
            set {
                this._BOYLAM = value;
            }
        }
    }
    
    [TableOptions(TableName="E_damlaucus_Form2_DataGrid1ML")]
    public class E_damlaucus_Form2_DataGrid1MLEntity : GridMLEntity<E_damlaucus_Form2_DataGrid1MLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _SEHIRLER;
        
        [ColumnOptionsAttribute(Name="SEHIRLER", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> SEHIRLER {
            get {
                return this._SEHIRLER;
            }
            set {
                this._SEHIRLER = value;
            }
        }
    }
    
    [TableOptions(TableName="E_damlaucus_Form2_DataGrid1SL")]
    public class E_damlaucus_Form2_DataGrid1SLEntity : GridSLEntity<E_damlaucus_Form2_DataGrid1SLEntity, E_damlaucus_Form2_DataGrid1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_Form2_DataGrid1SLML")]
    public class E_damlaucus_Form2_DataGrid1SLMLEntity : GridSLMLEntity<E_damlaucus_Form2_DataGrid1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_Form2VR")]
    public class E_damlaucus_Form2VREntity : VersionEntity<E_damlaucus_Form2VREntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_Form2RDC")]
    public class E_damlaucus_Form2RDCEntity : RDCEntity<E_damlaucus_Form2RDCEntity, E_damlaucus_Form2RDCMLEntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_Form2RDCML")]
    public class E_damlaucus_Form2RDCMLEntity : RDCMLEntity<E_damlaucus_Form2RDCMLEntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_Form2RD")]
    public class E_damlaucus_Form2RDEntity : RDEntity<E_damlaucus_Form2RDEntity, E_damlaucus_Form2RDMLEntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_Form2RDML")]
    public class E_damlaucus_Form2RDMLEntity : RDMLEntity<E_damlaucus_Form2RDMLEntity> {
    }
}




