//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace damlaucus.Entities {
    
    
    [TableOptions(TableName="E_damlaucus_Form1")]
    public class E_damlaucus_Form1Entity : FormEntity<E_damlaucus_Form1Entity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _BAGAJ;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _MIL;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _KILOBASIUCRET;
        
        private E_damlaucus_Form1VREntity _VersionEntity;
        
        private RDEntityCollection<E_damlaucus_Form1RDEntity, E_damlaucus_Form1RDMLEntity> _RD;
        
        private RDCEntityCollection<E_damlaucus_Form1RDCEntity, E_damlaucus_Form1RDCMLEntity> _RDC;
        
        private GridEntityCollection<E_damlaucus_Form1_DataGrid1Entity, E_damlaucus_Form1_DataGrid1MLEntity, E_damlaucus_Form1_DataGrid1SLEntity, E_damlaucus_Form1_DataGrid1SLMLEntity> _E_damlaucus_Form1_DataGrid1;
        
        public E_damlaucus_Form1Entity() {
            this.VersionEntity = new E_damlaucus_Form1VREntity();
            this.RD = new RDEntityCollection<E_damlaucus_Form1RDEntity, E_damlaucus_Form1RDMLEntity>();
            this.RDC = new RDCEntityCollection<E_damlaucus_Form1RDCEntity, E_damlaucus_Form1RDCMLEntity>();
            this.E_damlaucus_Form1_DataGrid1 = new GridEntityCollection<E_damlaucus_Form1_DataGrid1Entity, E_damlaucus_Form1_DataGrid1MLEntity, E_damlaucus_Form1_DataGrid1SLEntity, E_damlaucus_Form1_DataGrid1SLMLEntity>();
            this.E_damlaucus_Form1_DataGrid1.MLEntityEnabled = true;
            this.E_damlaucus_Form1_DataGrid1.SLEntityEnabled = false;
        }
        
        [ColumnOptionsAttribute(Name="BAGAJ", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> BAGAJ {
            get {
                return this._BAGAJ;
            }
            set {
                this._BAGAJ = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="MIL", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> MIL {
            get {
                return this._MIL;
            }
            set {
                this._MIL = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="KILOBASIUCRET", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> KILOBASIUCRET {
            get {
                return this._KILOBASIUCRET;
            }
            set {
                this._KILOBASIUCRET = value;
            }
        }
        
        public E_damlaucus_Form1VREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_damlaucus_Form1RDEntity, E_damlaucus_Form1RDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_damlaucus_Form1RDCEntity, E_damlaucus_Form1RDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public GridEntityCollection<E_damlaucus_Form1_DataGrid1Entity, E_damlaucus_Form1_DataGrid1MLEntity, E_damlaucus_Form1_DataGrid1SLEntity, E_damlaucus_Form1_DataGrid1SLMLEntity> E_damlaucus_Form1_DataGrid1 {
            get {
                return this._E_damlaucus_Form1_DataGrid1;
            }
            set {
                this._E_damlaucus_Form1_DataGrid1 = value;
            }
        }
    }
    
    [TableOptions(TableName="E_damlaucus_Form1_DataGrid1")]
    public class E_damlaucus_Form1_DataGrid1Entity : GridEntity<E_damlaucus_Form1_DataGrid1Entity, E_damlaucus_Form1_DataGrid1MLEntity, E_damlaucus_Form1_DataGrid1SLEntity, E_damlaucus_Form1_DataGrid1SLMLEntity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _ID1;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _ENLEM;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _BOYLAM;
        
        public E_damlaucus_Form1_DataGrid1Entity() {
        }
        
        [ColumnOptionsAttribute(Name="ID1", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> ID1 {
            get {
                return this._ID1;
            }
            set {
                this._ID1 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="ENLEM", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> ENLEM {
            get {
                return this._ENLEM;
            }
            set {
                this._ENLEM = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="BOYLAM", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> BOYLAM {
            get {
                return this._BOYLAM;
            }
            set {
                this._BOYLAM = value;
            }
        }
    }
    
    [TableOptions(TableName="E_damlaucus_Form1_DataGrid1ML")]
    public class E_damlaucus_Form1_DataGrid1MLEntity : GridMLEntity<E_damlaucus_Form1_DataGrid1MLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _SEHIRLER;
        
        [ColumnOptionsAttribute(Name="SEHIRLER", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> SEHIRLER {
            get {
                return this._SEHIRLER;
            }
            set {
                this._SEHIRLER = value;
            }
        }
    }
    
    [TableOptions(TableName="E_damlaucus_Form1_DataGrid1SL")]
    public class E_damlaucus_Form1_DataGrid1SLEntity : GridSLEntity<E_damlaucus_Form1_DataGrid1SLEntity, E_damlaucus_Form1_DataGrid1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_Form1_DataGrid1SLML")]
    public class E_damlaucus_Form1_DataGrid1SLMLEntity : GridSLMLEntity<E_damlaucus_Form1_DataGrid1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_Form1VR")]
    public class E_damlaucus_Form1VREntity : VersionEntity<E_damlaucus_Form1VREntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_Form1RDC")]
    public class E_damlaucus_Form1RDCEntity : RDCEntity<E_damlaucus_Form1RDCEntity, E_damlaucus_Form1RDCMLEntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_Form1RDCML")]
    public class E_damlaucus_Form1RDCMLEntity : RDCMLEntity<E_damlaucus_Form1RDCMLEntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_Form1RD")]
    public class E_damlaucus_Form1RDEntity : RDEntity<E_damlaucus_Form1RDEntity, E_damlaucus_Form1RDMLEntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_Form1RDML")]
    public class E_damlaucus_Form1RDMLEntity : RDMLEntity<E_damlaucus_Form1RDMLEntity> {
    }
}




