//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace damlaucus.Entities {
    
    
    [TableOptions(TableName="E_damlaucus_AnaForm")]
    public class E_damlaucus_AnaFormEntity : FormEntity<E_damlaucus_AnaFormEntity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _TOPLAMG;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _BAGAJG;
        
        private E_damlaucus_AnaFormVREntity _VersionEntity;
        
        private RDEntityCollection<E_damlaucus_AnaFormRDEntity, E_damlaucus_AnaFormRDMLEntity> _RD;
        
        private RDCEntityCollection<E_damlaucus_AnaFormRDCEntity, E_damlaucus_AnaFormRDCMLEntity> _RDC;
        
        private MLEntityCollection<E_damlaucus_AnaFormMLEntity> _ML;
        
        private SLEntityCollection<E_damlaucus_AnaFormSLEntity, E_damlaucus_AnaFormSLMLEntity> _SL;
        
        public E_damlaucus_AnaFormEntity() {
            this.ML = new MLEntityCollection<E_damlaucus_AnaFormMLEntity>();
            this.VersionEntity = new E_damlaucus_AnaFormVREntity();
            this.RD = new RDEntityCollection<E_damlaucus_AnaFormRDEntity, E_damlaucus_AnaFormRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_damlaucus_AnaFormRDCEntity, E_damlaucus_AnaFormRDCMLEntity>();
            this.SL = new SLEntityCollection<E_damlaucus_AnaFormSLEntity, E_damlaucus_AnaFormSLMLEntity>();
        }
        
        [ColumnOptionsAttribute(Name="TOPLAMG", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> TOPLAMG {
            get {
                return this._TOPLAMG;
            }
            set {
                this._TOPLAMG = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="BAGAJG", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> BAGAJG {
            get {
                return this._BAGAJG;
            }
            set {
                this._BAGAJG = value;
            }
        }
        
        public E_damlaucus_AnaFormVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_damlaucus_AnaFormRDEntity, E_damlaucus_AnaFormRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_damlaucus_AnaFormRDCEntity, E_damlaucus_AnaFormRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_damlaucus_AnaFormMLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
        
        public SLEntityCollection<E_damlaucus_AnaFormSLEntity, E_damlaucus_AnaFormSLMLEntity> SL {
            get {
                return this._SL;
            }
            set {
                this._SL = value;
            }
        }
    }
    
    [TableOptions(TableName="E_damlaucus_AnaFormML")]
    public class E_damlaucus_AnaFormMLEntity : MLEntity<E_damlaucus_AnaFormMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _SOYAD;
        
        private Bimser.Framework.Domain.DataField<string> _AD;
        
        [ColumnOptionsAttribute(Name="SOYAD", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> SOYAD {
            get {
                return this._SOYAD;
            }
            set {
                this._SOYAD = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="AD", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> AD {
            get {
                return this._AD;
            }
            set {
                this._AD = value;
            }
        }
    }
    
    [TableOptions(TableName="E_damlaucus_AnaFormSL")]
    public class E_damlaucus_AnaFormSLEntity : SLEntity<E_damlaucus_AnaFormSLEntity, E_damlaucus_AnaFormSLMLEntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_AnaFormSLML")]
    public class E_damlaucus_AnaFormSLMLEntity : SLMLEntity<E_damlaucus_AnaFormSLMLEntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_AnaFormVR")]
    public class E_damlaucus_AnaFormVREntity : VersionEntity<E_damlaucus_AnaFormVREntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_AnaFormRDC")]
    public class E_damlaucus_AnaFormRDCEntity : RDCEntity<E_damlaucus_AnaFormRDCEntity, E_damlaucus_AnaFormRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_AnaFormRDCML")]
    public class E_damlaucus_AnaFormRDCMLEntity : RDCMLEntity<E_damlaucus_AnaFormRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_AnaFormRD")]
    public class E_damlaucus_AnaFormRDEntity : RDEntity<E_damlaucus_AnaFormRDEntity, E_damlaucus_AnaFormRDMLEntity> {
    }
    
    [TableOptions(TableName="E_damlaucus_AnaFormRDML")]
    public class E_damlaucus_AnaFormRDMLEntity : RDMLEntity<E_damlaucus_AnaFormRDMLEntity> {
    }
}




